### ISSUE TITLE
cant show CPU&GPU temperature

### ISSUE THREAD

**Issue by Marcus-Lacia** [GeorgeGedox/GDash#1]
![image](https://user-images.githubusercontent.com/65057243/173193170-59f4e604-f202-45e4-b353-6486e0791dc6.png)

it cant show CPU&GPU temperature.

**Comment by GeorgeGedox** [comment]
HWiNFO64 needs to be running in the background for that to work. I haven't gotten yet into properly documenting my modifications to this project
